# Generated by Django 4.1.5 on 2023-01-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mydata",
            name="image",
            field=models.ImageField(default=" ", upload_to="portfolio/"),
            preserve_default=False,
        ),
    ]
